version: '3.8'

services:
  client:
    image: ${DOCKER_USERNAME}/mirror-dash-client:${TAG:-latest}
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - server

  server:
    image: ${DOCKER_USERNAME}/mirror-dash-server:${TAG:-latest}
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
